export default [
  [
    { letter: 'q', id: 0 },
    { letter: 'w', id: 1 },
    { letter: 'e', id: 2 },
    { letter: 'r', id: 3 },
    { letter: 't', id: 4 },
    { letter: 'y', id: 5 },
    { letter: 'u', id: 6 },
    { letter: 'i', id: 7 },
    { letter: 'o', id: 8 },
    { letter: 'p', id: 9 },
  ],
  [
    { letter: 'a', id: 10 },
    { letter: 's', id: 11 },
    { letter: 'd', id: 12 },
    { letter: 'f', id: 13 },
    { letter: 'g', id: 14 },
    { letter: 'h', id: 15 },
    { letter: 'j', id: 16 },
    { letter: 'k', id: 17 },
    { letter: 'l', id: 18 },
    { letter: 'ñ', id: 19 },
  ],
  [
    { letter: 'Enviar', id: 20 },
    { letter: 'z', id: 21 },
    { letter: 'x', id: 22 },
    { letter: 'c', id: 23 },
    { letter: 'v', id: 24 },
    { letter: 'b', id: 25 },
    { letter: 'n', id: 26 },
    { letter: 'm', id: 27 },
  ],
]
